### ISSUE TITLE
Meyda version increment

### ISSUE THREAD

**Issue by hughrawlinson** [vcync/modV#1]
Hola :guitar: 

Meyda's quite a lot further along now than where it was in the initial integration. We're on npm now, and we've done a lot of thinking about improvements to the API, so it's likely that you'll find them very useful :smile: We haven't added any new audio features, but that's the next step, so it's probably worth pulling in the dependency from npm so you can keep them up to date. I'm pretty sure your implementation doesn't care what audio features meyda provides, so if we add them you can just write modV patches that use them without having to modify modV core at all?

**Comment by 2xAA** [comment]
Sweet, thanks! I've actually manually updated Meyda on the Dev and UI branches, but I'll install it as a dependancy instead so when the time comes to push back to the main branch, everything will sync nicely 👌

**Comment by 2xAA** [comment]
Thanks to your hard work today @hughrawlinson I can now close this :D
