### ISSUE TITLE
Why is there no MIDIModule?

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#11]
the title

**Comment by 2xAA** [comment]
The layers branch has experimental MIDI parameter control on range inputs. Right click one ;)

**Comment by TimPietrusky** [comment]
Oh wow! Can I also enable / disable layers with that? Or the opacity?

**Comment by 2xAA** [comment]
Not yet.

**Comment by TimPietrusky** [comment]
👎

**Comment by 2xAA** [comment]
Spec for a MIDI "module" needs to be considered at this point - do we really need a MIDI module type? Could the same thing fall under the Script Module type?

**Comment by 2xAA** [comment]
I'm going to close this, no specific MIDI "Module" will be built, but overall MIDI support should be developed. The 1.5 milestone hopes to achieve this, see #24 for more info.
