### ISSUE TITLE
Save the settings of a plugin

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#152]
## Issue description

It would be nice so also save the settings for a plugin permanently, for example into preset or localStorage or another settings-file. 

Right now the settings are lost when the app is reloaded

## Version

modV: 2.0.0

**Comment by 2xAA** [comment]
Good suggestion!

I'd like to see this in the form of a modV settings file I think, since plugins will most likely not need to change with the preset.

Maybe some sort of checkbox option to allow plugins to save data into presets would be a good idea also for those all-too-likely edge-cases.

**Comment by TimPietrusky** [comment]
@2xAA Can you point me into a direction regarding the plugins? Are they saved in the store? Are presets also in the store? Can I distinguish between them? 

A reference to a file handling all of this would be nice or relevant documentation.

**Comment by 2xAA** [comment]
The MediaManager will have to undergo a significant rewrite to allow plugins to save their own settings data. This is a good thing regardless as the MediaManager codebase is pretty old/bad.

**Comment by TimPietrusky** [comment]
## Discussion from #178 

* Should plugin data be saved to presets
* Can presets save their own data to separate config JSON files
