### ISSUE TITLE
Save MIDI assignments into preset

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#153]
## Issue description
When doing some MIDI assignments and creating a new preset afterwards, the assignments are not saved into the preset.

This makes using MIDI impossible, because I don't want to loose the assignments every time I reload modV.

## Steps to reproduce
* Add a module
* Add a MIDI assignment to the module, for example for the "enable" button and a slider inside the module
* Create a new preset
* Reload modV
* Load the preset

## Versions
* modV 2.0-grabCanvas

**Comment by 2xAA** [comment]
This is almost the same issue as #152.

I think if #152 is fixed, this issue should also be fixed - do you think it's appropriate if I mark this as a duplicate?

**Comment by TimPietrusky** [comment]
Yes, I think so too. But please let's keep this open as a reference based on what you tell me in #152

**Comment by 2xAA** [comment]
This should be fixed by 03403f5 which allows plugins to define two methods, one to save data into presets and the other to load data back from presets.
