### ISSUE TITLE
How to run the production build?

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#166]
I created the build with `npm build` but I have no idea how to run it based on what is written in the README.md.

**Comment by 2xAA** [comment]
If the NWJS build was successful you can run modV as an application.
This can be found in the `./nwjs/build/modV` folder and will run modV and the Media Manager together for you.

Alternatively, you can serve the site built in `./dist` with any server application.
I use [reload](https://www.npmjs.com/package/reload).

Note, you will have to run the Media Manager separately using:
`node .\node_modules\modv-media-manager\run.js`

**Comment by TimPietrusky** [comment]
How can I be sure that the NWSJS build was successful? Because I have the folder you described, in there is `osx64` and `win64`. When I go into `osx64`, I find the `modV` executable. But when I start it, I only get this:

![screen shot 2018-06-19 at 13 39 56](https://user-images.githubusercontent.com/492378/41595219-4cc8b0ca-73c6-11e8-8b93-2abc70316957.png)

OS: OS X, El Capitan, 10.11.6 (15G21013)

**Comment by 2xAA** [comment]
Can you post the console output of the build process? (You can skip the `Zipping` block)

**Comment by TimPietrusky** [comment]
```
building nwjs...Create release folder in /Users/timpietrusky/Development/workspaces/node/modV_forked/nwjs/build/modV/win64
Create release folder in /Users/timpietrusky/Development/workspaces/node/modV_forked/nwjs/build/modV/osx64
⠏ building nwjs...{ Error: spawn wine ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn wine',
  path: 'wine',
  spawnargs: 
   [ '/Users/timpietrusky/Development/workspaces/node/modV_forked/node_modules/rcedit/bin/rcedit.exe',
     '/Users/timpietrusky/Development/workspaces/node/modV_forked/nwjs/build/modV/win64/modV.exe',
     '--set-version-string',
     'FileDescription',
     'modV' ] }
```

So I guess I have to install wine? Or can I somehow only build the osx version?

**Comment by 2xAA** [comment]
You can either install Wine (but only necessary for win64) or edit build.js here to remove win64 from the platform list https://github.com/2xAA/modV/blob/2.0/build/build.js#L47.

This should really be a separate build process with arguments for each platform.
Or ideally just a CI thing on version releases... but anyway.

**Comment by TimPietrusky** [comment]
I removed win64 from build/build.js and now it’s working!

**Comment by 2xAA** [comment]
Documentation can be found in the README, however additional documentation and build commands should be written/added.

https://github.com/2xAA/modV#notes-on-building
