### ISSUE TITLE
Error while building modV on Windows 10

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#167]
When installing modV by using `yarn` or `npm install` on Windows 10 I was receiving the following error because of `node-sass`:

```
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe"
```

This can be solved by installing the windows-build-tools like this in a terminal with Admin-rights:

```
npm install --global --production windows-build-tools
```

This should be mentioned somewhere so that people on Windows don't run into the same problem.

**Comment by TimPietrusky** [comment]
If you have all of that above and it’s still failing because node-gyp can’t find some libsass src files: Your node Version might be too high for node-sass. 

In my case I was using node 10. The fix was to use node-sass latest, but that is just a quick fix.

**Comment by 2xAA** [comment]
modV need some serious work on its documentation. Sorry about this.
Will add asap!

**Comment by TimPietrusky** [comment]
It’s totally fine, I’m just adding everything I can to address this problem so we can fix it for other people!

**Comment by TimPietrusky** [comment]
The problem is still there in modV 2.0. The version of node-sass is still outdated.

**Comment by 2xAA** [comment]
Would you mind creating a PR to fix this if you already found a fix?

**Comment by TimPietrusky** [comment]
Yes!

**Comment by TimPietrusky** [comment]
@2xAA How should we handle the documentation part of this issue? 

- [ ] README
- [ ] https://dist-sygidsulny.now.sh (How can I get access to this?)
- [ ] #238 
- [ ] #56 
- [ ] WIKI on GitHub

Anything else?

**Comment by 2xAA** [comment]
@TimPietrusky You should add this to the documentation feature branch: https://github.com/m-o-d-v/modV/pull/268
