### ISSUE TITLE
MediaManager is not started when running the build version

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#168]
I was able to build modV on Windows 10 and run it. But the MediaManager is not started, I had to manually start it by executing `node .\node_modules\modv-media-manager\run.js`.

I started modV like this: modV\nwjs\build\modV\win64

**Comment by TimPietrusky** [comment]
This is working when using the OSX build, meaning that the media manager is started there.

**Comment by lezsakdomi** [comment]
Same with linux build
