### ISSUE TITLE
GrabCanvas: No error for LuminaveConnector message when deactivated

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#186]
When the grabCanvas plugin is disabled, it should not try to reconnect to the Luminave WebSocket server.

**Comment by TimPietrusky** [comment]
The problem is in https://www.npmjs.com/package/reconnecting-websocket, it's not possible to stop reconnecting by using this:

```
this.connection.close();
```

**Comment by TimPietrusky** [comment]
I created https://github.com/pladaria/reconnecting-websocket/issues/70 to ask if this might be a problem in the underlying library that we are using.

**Comment by TimPietrusky** [comment]
Implemented this myself in #219 because I couldn't find a solution ANYWHERE!

**Comment by 2xAA** [comment]
Fixed!
