### ISSUE TITLE
Start a Wiki that actually describes the undergoing concepts of modV

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#195]
* default profile "could" be something like a "project", but you can't create it in modV as of now

**Comment by martinberlin** [comment]
I second that! Please also add more detailed information about the build process. After reading [the getting started section](https://modv.js.org/guide/#system-requirements) I still could not get it to run on Linux (Ubuntu)
All build process runs, then opens localhost:8080 with a blank page.
TypeError: __WEBPACK_IMPORTED_MODULE_2__main__.default is undefined app.js 6979

**Comment by TimPietrusky** [comment]
As we are moving away from modV 2 and are working on modV 3, the wiki was wiped as we are putting all docs onto https://modv.vcync.gl/v3/guide

@martinberlin would you mind trying modV 3 and if that is not working for you, open a new ticket?

**Comment by martinberlin** [comment]
At the end it worked out!  But not complete. Anyways for sure will try the next version
