### ISSUE TITLE
Use Projects instead of profiles

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#207]
Projects need to be global to modV, otherwise they serve no special purpose

- [x] Profiles should be called "Projects"
- [x] A plugin should also be saved in the project context (like everything else)
- [x] If I load a project, all my special settings are there
- [x] Remove the "profile" switch in the "presets" view
- [x] UI element to load a project
- [x] Projects should be able to be created from the UI
- [x] Load last project automatically after reload of modV

**Comment by 2xAA** [comment]
Updated to tasklist.

**Comment by TimPietrusky** [comment]
Thank you super much! 🔥
