### ISSUE TITLE
Save module state into preset

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#22]
* Disable a module
* Change a configuration value of a module
* Save a a preset
* Load the preset

-> The module is enabled again & all the configurations have default values. 

The desired behaviour should be, that the module is disabled and the configuration is loaded from the saved preset.

Maybe add a button "default values" into every module, so someone can overwrite the loaded configuration values?

**Comment by 2xAA** [comment]
Graphically every value is set to default, but the actual values of the modules are saved.
Try disabling the module and enabling it again after you've loaded the preset, your values have been stored.

Even the module which appears to be enabled is still disabled.

This is either an issue with the loadPreset function, the module creation or the Module Controls not parsing existing values.

Should be a fairly quick fix.
Thanks for reporting!

**Comment by TimPietrusky** [comment]
Yes!

I also encountered the bug while using the *Text* module: 
* The value is saved into the preset
* When I load the preset, the value is still on the screen
* But it doesn't get loaded into the UI (it shows the default *modV* value)

**Comment by 2xAA** [comment]
Fixes for TextControls, CheckboxControls, SelectControls and RangeControls have been pushed into the master branch.

This changes preset loading and saving for values that have appended content - most notably the Text module. Any previous text sizes load from presets will now be invalid - sorry! Though a quick remedy is to load your preset and save it again.

**Comment by 2xAA** [comment]
Fixes for internal Module controls (Opacity, Enable toggle and Blend Mode) have also been added to the Master Branch.

**Comment by TimPietrusky** [comment]
THANK YOU! 

Will try it out AFTER the NYE gig 😍

**Comment by 2xAA** [comment]
This has been fixed, I'm gonna close this.

**Comment by TimPietrusky** [comment]
Yes, this is working and was tested @frankenjs 👯🦄😎
