### ISSUE TITLE
GrabCanvas: Resize preview

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#23]
Right now the **preview view** will not be resized when the **output view** is resized. 

The **output view** only gets resized after changing the size of the main window.

**Comment by 2xAA** [comment]
The GrabCanvas Module requires some extensive work.
I have a Teensy 3.0 and will install the FadeCandy firmware onto this to test as soon as I can.

**Comment by 2xAA** [comment]
8fe5506 re-writes GrabCanvas to a modV 2.0 Plugin. I think this fixes the issue - can you confirm?

**Comment by TimPietrusky** [comment]
This is working with the new module.

**Comment by TimPietrusky** [comment]
I think it is not fixed, sorry for closing this. I had the same problem right now. Have to reproduce it and maybe open a new issue, because I'm not sure if it's actually the same issue.

**Comment by TimPietrusky** [comment]
I tested this very extensive and the problem does not exist anymore.
