### ISSUE TITLE
Project Gallery component incorrectly references variable

### ISSUE THREAD

**Issue by 2xAA** [vcync/modV#232]
Remove variable reference to squish error

**Comment by TimPietrusky** [comment]
@2xAA What was the error you were referencing to?

**Comment by 2xAA** [comment]
`loading` wasn't defined on the Project Gallery component, so Vue threw a warning/error each time the component was loaded.

**Comment by 2xAA** [comment]
@TimPietrusky `loading` wasn't defined on the Project Gallery component, so Vue threw a warning/error each time the component was loaded.

**Comment by TimPietrusky** [comment]
@2xAA I can't see an error / warning related to the Project Gallery anymore, so I think this is fixed.
