### ISSUE TITLE
Load/Save preset based on MIDI input

### ISSUE THREAD

**Issue by 2xAA** [vcync/modV#235]
Use case:

I want to have a multiple presets in a project and when the music is changing, I want to load another preset that should be run then, change some stuff in that preset and load another preset again. Then at some point in time I want to load the preset that was saved earlier. All of this should happen using MIDI.

**Comment by 2xAA** [comment]
@TimPietrusky - converted this note into an issue.

This should be possible using a plugin actually.

I'm thinking at this point, modV bundles with some core functionality written as plugins which you can't edit/turn off and then once modV has started, any loaded from the Media Manager™ then appear in the gallery view.

**Comment by TimPietrusky** [comment]
@2xAA This is related to #29 and #38 am I right?

**Comment by 2xAA** [comment]
#38 Yes, though I think it should be a separate issue.

Not really #29 as much.

Plugins are/should be flexible enough to implement almost whatever you want.
Creating a plugin for this should be fairly straight forward.

It's possible to communicate with the whole store in a plugin, so loading, saving, listing Project presets should be pretty easy.
