### ISSUE TITLE
All modules are enabled when moving a new module into a layer

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#243]
## Issue
All modules that are part of a layer are "enabled" when a new module is dragged into the layer when their previous state was "disabled". And this is only happening on the checkbox-input, the actual state of the module is still disabled

## Steps to reproduce
* Add a module into the layer, for example the `Text`
* Enable the `Text` module
* Disable the `Text` module
* Move another module into the same layer, for example `Ball`

## Versions
* modV-2.0-drawloop

**Comment by 2xAA** [comment]
This seems to be an issue with buefy's (the UI library modV uses) checkbox component.

It could be a combination of this component and the fact that vue-draggable (Sortable) is, at this point, pretty garbage - Sortable isn't being maintained anymore.

I'm not too worried if this is to do with Sortable or not, as I'm aiming to replace Sortable with [vue-smooth-dnd](https://kutlugsahin.github.io/vue-smooth-dnd/), which seems much nicer and a lot more flexible.
