### ISSUE TITLE
Can't scroll in tab-view

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#260]
When opening any tab-view, it is impossible to scroll anymore. This makes it impossible to reach modules or plugins that are on the bottom of the page. 

## Versions
modV: 2.0
Chrome: 69
OS: Windows & macOS

**Comment by 2xAA** [comment]
Temporary work around until I have the time to fix this, zoom the page out - sorry.

**Comment by TimPietrusky** [comment]
Yeah that is what I was doing, but I have too many midi assignments! Had to tweak some elements with the dev console to get to where I wanted to go.

**Comment by TimPietrusky** [comment]
The proposed workaround with zooming out is not working for modules, so what I did is to add some CSS in the devconsole to `<div class="module-gallery columns is-multiline vb-content">`:

```css
  position: fixed;
  z-index: 1337;
  overflow: scroll;
  width: 80%;
```
