### ISSUE TITLE
Plugin: AutoSave

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#264]
It would be nice to have a plugin that does auto-saving projects / presets every 5 seconds, so that when modV is crashing because of a bug or when you just forget to save after you did a live set, your preset would not be lost.

**Comment by 2xAA** [comment]
This could be a plugin 😂

**Comment by TimPietrusky** [comment]
@2xAA you think so? :D

**Comment by 2xAA** [comment]
Haha, yes. I totally didn't see that you already said it should be a plugin 😓 
>It would be nice to have a plugin that does auto-saving projects
