### ISSUE TITLE
Define modV Plugin Structure (+modV's future)

### ISSUE THREAD

**Issue by 2xAA** [vcync/modV#29]
After talking with @TimPietrusky at FrankenJS about modV's future, it became clear a plugin API would be very useful.

Features such as a live code editor, Palette and asset managers etc. would benefit from being separate from modV's core code. As it is, modV has a fairly large codebase already.
Writing these as Plugins will allow future extension of modV and keep extra features written be potential users outside of modV Module types.

To begin with, a full writeup of modV's current API and inner workings is essential.
This (the writeup) will not happen until the end of the 1.5 milestone.

Plugin functionality may come before 2.0 as I'm thinking 2.0 may become the "UI" update and the final move to NWJS as the main target for modV.

It is clear a roadmap is required.

**Comment by Rumyra** [comment]
Ooo - I was gonna start with some live code editor, so let me know how you're implementing!

Have also spoken to @TimPietrusky about his granduoso ideas of plugins. It's totally a goody 👍

**Comment by TimPietrusky** [comment]
Super much agree to what I talked about with @2xAA and @Rumyra!

I would love to write a MIDI plugin to handle various MIDI controllers and provide a UI to see the assignments of each physical control. 

And I would love to create a remote control aka virtual MIDI controller, to control modV from a touch enabled device / VR.

**Comment by 2xAA** [comment]
After reading a few articles and watching a talk on plugin systems I've concluded that an Event Emitter system is probably the way to go.

modV has many separate components:

* modV's internal lifecycle
* Module lifecycles
* Control lifecycles
* MIDI events
* (upcoming) Plugin lifecycles

To try and keep Plugins as free and open-ended as possible I've decided to let the developer determine the best structure for their Plugin.

The only requirement will be that it is written as a Class and extends from the upcoming modV.Plugin Class so modV can handle IDs, the initalisation, loading and listing of Plugins.

#38 and #39 cover this, but I'll keep this open for now.

**Comment by TimPietrusky** [comment]
Yes, makes super much sense!

**Comment by 2xAA** [comment]
This now makes absolutely no sense `¯\_(ツ)_/¯`

I've taken inspiration from [Vue.js' plugin structure](https://vuejs.org/v2/guide/plugins.html) and created this draft spec (which is implemented in 2.0): https://github.com/2xAA/modV/wiki/%5BDRAFT%5D-%5B2.0%5D-Plugin

Branch [2.0-plugins](https://github.com/2xAA/modV/tree/2.0-plugins) has the latest version at the moment.
