### ISSUE TITLE
Where to put my custom 2D module?

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#299]
I tried to follow the [documentation](https://modv.js.org/guide/writingA2DModule.html#_1-export-an-object), but it doesn't say where I should put my custom module.

**Comment by 2xAA** [comment]
Ah, that's a flaw for sure.

Should go in the module folder in the media directory:
https://modv.js.org/guide/mediaManager.html#media-folder

Documentation needs updating.

**Comment by 2xAA** [comment]
I think https://github.com/vcync/modV/pull/268/commits/d6236ef602faf3d0848ed34ee13beed3fec6fa00 fixed this, can you confirm @TimPietrusky? Thanks.

**Comment by TimPietrusky** [comment]
@TimPietrusky Yes, that fixes my problem! But this has to be deployed yet, right?

**Comment by 2xAA** [comment]
We have Travis doing automatic deployments on the documentation branch right now. Should have deployed already.
