### ISSUE TITLE
jsfft breaking Meyda breaking modV

### ISSUE THREAD

**Issue by 2xAA** [vcync/modV#30]
modV is currently broken an all platforms, please bear with this while Meyda is broken.
Currently trying to diagnose the problem myself and create a PR, however the issue seems elusive.

Track this progress on Meyda's issues page: https://github.com/hughrawlinson/meyda/issues
Currently keeping up to date on this in https://github.com/hughrawlinson/meyda/issues/138 :)

**Comment by nevosegal** [comment]
So yeah - https://github.com/dntj/jsfft/issues/8
I'm going to try and integrate my fft library with Meyda during the weekend, sorry about that!

**Comment by 2xAA** [comment]
Good luck Nevo!

**Comment by 2xAA** [comment]
https://github.com/hughrawlinson/meyda/pull/194 fixes this (on 1.5)
