### ISSUE TITLE
Failed to compile with 2 errors: ArrayBufferDataStream & BlobBuffer were not found in /~/ccapture.js/build/CCapture.all.min.js

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#300]
## Steps to reproduce
* Clone 2.0
* `npm install`
* `npm start`

Gives you this error:

```
 ERROR  Failed to compile with 2 errors                                                                                                                              

These relative modules were not found:

* ./ArrayBufferDataStream in ./~/ccapture.js/build/CCapture.all.min.js
* ./BlobBuffer in ./~/ccapture.js/build/CCapture.all.min.js
```

**Comment by TimPietrusky** [comment]
I did a new clone and the problem was not there anymore.

**Comment by 2xAA** [comment]
CCapture is set to be removed - see #294.

**Comment by 2xAA** [comment]
I don't know why this error occurs, I've seen it multiple times but it's not consistent.
Maybe a package-lock issue?

**Comment by 2xAA** [comment]
Closing as I can't consistently reproduce this - if there's a method to reproduce this then we can reopen and fix.
