### ISSUE TITLE
Context menu triggered on Module is creating an endless-loop

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#303]
## Issue description
When using the context menu on an module in the layers sidebar and the space to open the menu would be less than what is currently available, modV goes into an endless loop to open the menu. 

## Steps to reproduce
* Move any module (for example Text) into the Layer
* Click on the Text module
* The property view on the bottom opens
* Leave the height of the property view or decrease the height even more
* Rick click on a property, choose "Attach Feature" and see that modV is crashing

## Further information
I could see while using the dev tools that something is happening inside of https://github.com/vcync/modV/blob/2.0/src/extra/context-menu/Menu.vue#L63 and with that I mean that this is called over and over again. But I might be wrong.

**Comment by 2xAA** [comment]
If possible can you video this happening?
I can't seem to reproduce on macOS and I'm doubtful this is an OS specific issue, though I'm open to that being a possibility.

Just to show you how I was testing:
https://youtu.be/_mNoQhHlKPQ

**Comment by TimPietrusky** [comment]
It is only happening on Windows, it is not happening on macOS!

**Comment by 2xAA** [comment]
Super strange. I'll attempt to test soon, but I'm away from my Windows machine for a week or so now

**Comment by 2xAA** [comment]
Hey Tim, sorry to say but I'm still unable to reproduce this - even on Windows.
Are you able to video what's going on?

Here's my video of my Windows test (running as a Virtual Machine):
https://youtu.be/TvvopSXi6js

**Comment by TimPietrusky** [comment]
I never had this problem again, so I think this was something related to an old modV version + Chrome version or something else.

If anyone encounters this again, feel free to ping me and we will investigate again.
