### ISSUE TITLE
Properties with an expression are not rendered on the Canvas when loaded from preset

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#304]
## Issue Description
When I use an expression on any property, the value is restored from the preset (as defined in #279), but not represented in what is rendered on the canvas. 

## Steps to reproduce
* Put the Text module into the layer
* Add an expression to the size property like "value * 3"
* Set the sitze to 300
* Save the preset into "test text"
* Reload modV
* Load the "test text" preset
* See that the size + expression are loaded, but the rendered Text is still as small as it is when you load the Text module the first time

**Comment by 2xAA** [comment]
In the preset JSON, do you see the value 300?

Is this also the value (300) you expect to see loaded or would you expect 900?

**Comment by 2xAA** [comment]
I can't seem to reproduce this.

Following the steps provided I'm seeing the `Size` prop of `Text` being set to `900` when loading (because 300 * 3 = 900).

Would you mind trying again on the latest 2.0 commit of modV and confirming this is still an issue?

There is still an issue here however, because `300` is the value I was expecting but I'm seeing `900` instead.

**Comment by TimPietrusky** [comment]
@2xAA the original problem seems to be gone in the latest version of 2.0. 

Why would you expect 300? Isn't the value a reflection of the value entered after the expression was applied?

**Comment by 2xAA** [comment]
When saving, we want the base value (300) to be saved rather than the expression output, as the expression is also saved.

If 900 was saved, the initial value of the loaded preset would be `900 * 3` which isn't correct.

**Comment by TimPietrusky** [comment]
@2xAA I created #321 to keep track of the problems we currently have with expressions.
