### ISSUE TITLE
Modules without the "props" property can't be saved into a preset

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#305]
## Issue Description
When trying to save a module into a preset that doesn't has the `props` property, the preset can't be saved. 

## Steps to reproduce
* Put the MattiasCRT module into the layer
* Save the preset "test crt"
* See that the preset is not created, the name is still in the input field

**Comment by TimPietrusky** [comment]
My proposed solution would be to check if the module has the `props` property and if it doesn't, I would just an empty Object.

**Comment by 2xAA** [comment]
Sounds like a good solution. Can't think of any reason why this would break anything

**Comment by TimPietrusky** [comment]
Awesome, will do it then!
