### ISSUE TITLE
Loaded blending from preset is not visible in UI

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#306]
## Issue Description
When loading a saved blending / composition option from a preset, it seems to get set, but the input is still showing the default value which is `normal`. 

## Steps to reproduce
* Put a module into a layer, for example Text
* Set the blending to `multiply`
* Save a preset called "test blending"
* See that the blending is saved in the preset-json
* Reload modV
* Load the preset "test blending"
* See that the blending in the input is set to `normal`, but the actual blending is set to `multiply`

**Comment by 2xAA** [comment]
Some terrible choices were made on loading the Module's meta back in. I've rectified this and the loaded Module's blend mode now shows correctly in the UI. Awaiting the CI, then I'll merge.

**Comment by TimPietrusky** [comment]
Thank you so much for this simplification! I was looking at the code and I really couldn't figure out what was going wrong.
