### ISSUE TITLE
Attaching features to some Module properties cases modV to not render to Canvas anymore

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#307]
## Issue Description
When attaching audio features to the properties of modules, sometimes this is casing modV to not render to any output anymore. The module itself seems "hanging", as I can't change any property of the module anymore. When the module is removed, modV is still not rendering. When the module is added again, it is still "hanging". 

## Steps to reproduce
* Put "FractilianParabolicCircleInversion" into a layer
* Attach a feature to a property that doesn't produce any good outcome (TODO)

## Further Information
* I have to reproduce this on Windows again with a concrete example as my Mac can't render that Module

**Comment by 2xAA** [comment]
Some of Meyda's audio features output as Arrays.
We need to edit the audio features plugin to filter these from the dropdown.

**Comment by 2xAA** [comment]
According to [Meyda's documentation](https://meyda.js.org/audio-features), these are the features which return numeric values and are not arrays:

```
'rms',
'zcr',
'energy',
'spectralCentroid',
'spectralFlatness',
'spectralFlux',
'spectralSlope',
'spectralRolloff',
'spectralSpread',
'spectralSkewness',
'spectralKurtosis',
'loudness',
'perceptualSpread',
'perceptualSharpness',
```

**Comment by TimPietrusky** [comment]
Thank you!
