### ISSUE TITLE
Use Electron

### ISSUE THREAD

**Issue by 2xAA** [vcync/modV#328]
A move to Electron would be beneficial to not only our users but also it would force us to use Semver and pushing real updates.

The amount of Electron support and compatible libraries compared to NW.js is also extremely beneficial to us.

The biggest challenge to move to Electron was the fact we could not easily render new output windows because Electron would sandbox child windows and not allow access to the child's document, preventing the direct use of HTMLCanvas.

This has, apparently, been solved by removing the sandbox flag as discussed in this thread:
https://github.com/electron/electron/issues/1865#issuecomment-249989894

**Comment by Martin-Pitt** [comment]
Or rather, you may want to look at other webPref option:
> `nativeWindowOpen` Boolean (optional) - Whether to use native `window.open()`. Defaults to `false`. Child windows will always have node integration disabled unless `nodeIntegrationInSubFrames` is true. Note: This option is currently experimental.

Don't need to mess with sandbox and disabling node.js, sounds like a pain.

I'm very familiar with using Electron at work, although mostly for internal tools and apps for clients rather than packaging/distribution to public at large. Would be happy to help out.

**Comment by 2xAA** [comment]
Oops, sorry @Martin-Pitt - I hadn't seen this before now 😓.

We've started work on modV 3 over in https://github.com/vcync/modv-3. We'd love any input you have on our Electron setup there.

One issue in particular that would be good to figure out is https://github.com/vcync/modv-3/issues/187. If you have any insight that would be awesome :)
