### ISSUE TITLE
Image control is broken

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#329]
## Issue Description
After a putting an image into the `images` folder in the [media manager](https://modv.js.org/guide/mediaManager.html#location), it's not possible to select the `Images` tab in modV:

<img width="364" alt="screen shot 2019-02-28 at 22 06 25" src="https://user-images.githubusercontent.com/492378/53598480-25b87900-3ba5-11e9-91e2-544c98851018.png">

**Comment by TimPietrusky** [comment]
## Workaround

* [Find out where your modV media folder is located](https://modv.js.org/guide/mediaManager.html#location)
* Add the [Image.js module](https://gist.github.com/TimPietrusky/1eb559d1268e171fc27d78c2b974ada9) into your `media/<project>/modules` folder
* Open the `Image.js`using an Editor of your choice follow the instructions inside the file to add the label + name of the images you want to use
* Put the actual image files into the `media/<project>/images` folder
* Open modV
* Put the "Image" module into a layer
* In the options panel for the Image module, select the images you added into the Image.js

In the end it should look like this:

<img width="515" alt="screen shot 2019-02-28 at 22 37 40" src="https://user-images.githubusercontent.com/492378/53600316-93ff3a80-3ba9-11e9-9bc1-766b72564068.png">

Which gives you the possibility to add awesome filters to any image, like I did here for my Avatar:

<img width="621" alt="screen shot 2019-02-28 at 22 39 15" src="https://user-images.githubusercontent.com/492378/53600378-b98c4400-3ba9-11e9-9101-267098298753.png">

**Comment by nbirckel** [comment]
Thanks @TimPietrusky , it worked perfectly.

I just had to edit 
`          this.image.src = `http://localhost:3133/default/image/${value}`;`
to the right project name too.

**Comment by TimPietrusky** [comment]
@2xAA What are the plans to support this and videos in modV 3?

**Comment by TimPietrusky** [comment]
My proposed fix is for modV 3.0 as I think it makes no sense to put time into improving modV 2. What do you think @2xAA?
