### ISSUE TITLE
Configuration for build platforms

### ISSUE THREAD

**Issue by lezsakdomi** [vcync/modV#345]
One should be able to target linux systems without modifying the source code (i.e. [`./modV/build.js` line 47](https://github.com/vcync/modV/blob/2.0/build/build.js#L47)).

**Comment by martinberlin** [comment]
Hello Lezsakdomi,
can you please explain to me in a few lines how to make it run in Linux?  (I use Ubuntu 18)
I followed both getting started in modv.js.org and also the readme and could not get it to work.
Update: I know what it is, linux was opening it on firefox by default, and it only runs in Chrome. Could be really nice to display some message to advice the user to open it in Chrome.
Now just getting "X could not create output window" on start but I can preview things. Very nice design!

**Comment by TimPietrusky** [comment]
@martinberlin you have to allow "pop-up" windows, then the output window will open automatically.

**Comment by martinberlin** [comment]
Ahh ok, didn't get that, thanks. All these small things, including a warning message that you use a wrong browser will greatly help modV to be more user-friendly on first installations.
