### ISSUE TITLE
WebAudio TypeError

### ISSUE THREAD

**Issue by lezsakdomi** [vcync/modV#349]
![Screenshot from 2019-08-31 20-13-06](https://user-images.githubusercontent.com/8544161/64067615-df170a80-cc2b-11e9-9ec1-783e834ee1e5.png)

In the console the following error can be found:

| function | at | source |
| --- | --- | --- |
| Promise.then (async) |   |  |
| -- | -- | -- |
| start | @ | index.js?677e:117 |
| mounted | @ | main.js?1c90:75 |
| invokeWithErrorHandling | @ | vue.esm.js?65d7:1863 |
| callHook | @ | vue.esm.js?65d7:4222 |
| mountComponent | @ | vue.esm.js?65d7:4089 |
| Vue.$mount | @ | vue.esm.js?65d7:9057 |
| Vue.$mount | @ | vue.esm.js?65d7:11953 |
| Vue._init | @ | vue.esm.js?65d7:5021 |
| Vue | @ | vue.esm.js?65d7:5088 |
| (anonymous) | @ | main.js?1c90:68 |
| (anonymous) | @ | app.js:1899 |
| \_\_webpack_require\_\_ | @ | app.js:689 |
| fn | @ | app.js:110 |
| (anonymous) | @ | app.js:13166 |
| \_\_webpack_require\_\_ | @ | app.js:689 |
| (anonymous) | @ | app.js:790 |
| (anonymous) | @ | app.js:793 |

**Comment by TimPietrusky** [comment]
- When does this error come? With the build or the dev version?
- Which OS are you using?

**Comment by girlcheese** [comment]
You probably need to manually allow the localhost access to your camera and audio - this can be done in browser settings. Fixed it for me.

**Comment by 2xAA** [comment]
@girlcheese Do you know if this is a recent change? I've only just come across this.

**Comment by 2xAA** [comment]
To work around this, open this in Chrome: chrome://settings/content/siteDetails?site=http%3A%2F%2Flocalhost%3A8080

and allow camera and audio access.

Thank you @girlcheese.
