### ISSUE TITLE
ERROR  Failed to compile with 2 errors  

### ISSUE THREAD

**Issue by bmsdave** [vcync/modV#350]
I have error when i run `yarn run dev`:
```
These relative modules were not found:

* ./BlobBuffer in ./~/ccapture.js/build/CCapture.all.min.js
* ./ArrayBufferDataStream in ./~/ccapture.js/build/CCapture.all.min.js
> Listening at http://localhost:8080
```

system:
Linux 5.0.0-25-generic #26~18.04.1-Ubuntu SMP x86_64 GNU/Linux

Tell me, please, where can I get modules `ArrayBufferDataStream` and `BlobBuffer`?

**Comment by 2xAA** [comment]
This is a strange error with CCapture.
I'm going to submit a PR to remove this from modV at the moment, then rewrite CCapture to work properly in a browser environment.

This error only occurs sometimes though and I can't isolate _why_  this happens.

For now, you can comment out lines in `src/main.js` which have `capture` in them.

**Comment by bmsdave** [comment]
Thanks you! I used this workaround - https://github.com/vcync/modV/issues/348
