### ISSUE TITLE
Moving module doesn't move it

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#353]
## Problem
I have a preset and I want to move a module (in this case `Pixelate`) into another position in my layer. When I do this and save my preset, the module is saved in another position inside the preset-json, but loading my preset always puts the module in the position it was before I moved it. 

## Steps to reproduce
* Load my preset [default.zip](https://github.com/vcync/modV/files/3591734/default.zip)
* Move the pixelate module to the end of the layer
* Save my preset
* Reload modV
* Load my preset
* See that pixelate is at the same position as before

## What I did so far
* I removed the media folder and copied everything from the backup into the `default` project
* I restarted modV on the CLI, still the same problem

**Comment by TimPietrusky** [comment]
I tried to debug this:

- At this position the moduleOrder is wrong: https://github.com/vcync/modV/blob/2.0/src/components/Layer/index.vue#L126
- At this position the moduleOrder is correct: https://github.com/vcync/modV/blob/2.0/src/store/modules/projects.js#L98

What happens in between?

**Comment by 2xAA** [comment]
The preset is saving the correct "new" order but it somehow is loading in the last order from the UI, though there's no data saved to preserve the UI order in the preset or between application reload, so I think this bug isn't part of the preset saving.

**Comment by TimPietrusky** [comment]
@2xAA I think so too, the preset is correct, but when it's loaded in the vue component it is wrong. I also clone modV freshly, used a new browser and loaded the preset there: Same behavior.

**Comment by TimPietrusky** [comment]
I can confirm that #354 is fixing this problem!
