### ISSUE TITLE
Plugin: grab-canvas

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#366]
In modV2 we had the plugin grab-canvas that was used in combination with https://github.com/NERDDISCO/luminave to exchange color-information that is grabbed live from the output-canvas to control lights. 

## Idea: API via GraphQL

Maybe it would make sense to not directly connect to luminave over Websocket, but to provide an API via GraphQL that provides a subscription (which is also WebSocket), so that other applications could get that information out of modV, too.

## Dependency

vcync/modv-3#133 needs to be done if we want to make this a plugin, but maybe if we decide that modV needs a general GraphQL API, it would go into core.

**Comment by 2xAA** [comment]
@TimPietrusky, do you think we should split out the GraphQL idea into a separate issue?

**Comment by TimPietrusky** [comment]
@2xAA yes, that makes total sense!

**Comment by 2xAA** [comment]
> @2xAA yes, that makes total sense! 

oh good :)
