### ISSUE TITLE
Ball: The "wrap"-checkbox has no effect

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#368]
When activating "wrap" or deactivating it, the result is always the same = It's wrapped.

**Comment by 2xAA** [comment]
Investigating this shows the balls are always not wrapped, they bounced off the sides instead.

This is a regression from 2.0:
https://github.com/vcync/modV/blob/2.0/src/modv/sample-modules/Ball-2.0.js#L175

The Ball module in 3.0 completely removed `wrap` by accident.
