### ISSUE TITLE
Ball: The "size" has no effect, even when RMS/ZCR intensity is 0

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#369]
When setting `RMS/ZCR` to 0 and the size to 10, I would expect the balls to show up. But instead they are so small that you can't see them.

**Comment by 2xAA** [comment]
Yep, can see that this has changed from 2.0:
https://github.com/vcync/modV/blob/2.0/src/modv/sample-modules/Ball-2.0.js#L162

3.0:
https://github.com/vcync/modV/blob/main/src/application/sample-modules/Ball.js#L203
