### ISSUE TITLE
Add auto-updater

### ISSUE THREAD

**Issue by 2xAA** [vcync/modV#371]
Implement updater into modV from this guide

https://www.electronjs.org/docs/tutorial/updates

**Comment by 2xAA** [comment]
@TimPietrusky What is the next step for this issue? I feel we’re close to completing this.

**Comment by TimPietrusky** [comment]
@2xAA I can't get it to work in Travis, I will update my own Mac to the latest version of MacOS and see if I can get it to work there and then try to find out what the problem with Travis is.

**Comment by 2xAA** [comment]
@TimPietrusky Could you please link the Travis log?

**Comment by TimPietrusky** [comment]
I updated my Mac to the latest MacOS and will now try to build it. 

I had to install the xcode-cli tools in order that the build runs: `xcode-select --install`

**Comment by TimPietrusky** [comment]
It will still fail as the option `--strict` is still not working. It works when it is removed. I opened https://github.com/electron-userland/electron-builder/issues/5163 to find out how to disable the option via the electron-builder configuration.

**Comment by TimPietrusky** [comment]
We had to remove grandiose as a dependency and disabled NDI so that no one is confused why this is not doing anything. Will be added again in #413

**Comment by TimPietrusky** [comment]
Just for reference: I was also using https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/v1/docs/guide/recipes.md to understand which changes had to be made.

**Comment by TimPietrusky** [comment]
@2xAA ~~Would you mind to also add the required certificates for Windows?~~ I just saw how expensive this is, I guess we can just disable code-signing for windows. 

Also we need to look into https://github.com/electron-userland/electron-builder/issues/3629 & https://travis-ci.community/t/codesigning-on-windows/1385/4 to get the Windows-signing to work on Travis

**Comment by 2xAA** [comment]
@TimPietrusky yes I think we should disable code signing for Windows. That's ludicrously expensive 😰

**Comment by TimPietrusky** [comment]
@2xAA Already did, testing the build right now!

**Comment by TimPietrusky** [comment]
The generated dmg is still not "signed" or at least it shows the same stupid message on MacOS once you open modV.

**Comment by 2xAA** [comment]
Now that we have a Notarized app being built through Travis we are very close to completing this issue.

But, before closing:

1. We should make sure users can manually trigger an update check from the menu-bar.

2. After that addition we should test updates are working with a point release.

**Comment by 2xAA** [comment]
This has now been implemented, however electron-builder tries to publish to the Snap store for Linux which is breaking the latest-linux.yml upload to GH Releases, breaking auto-updating on Linux.

We need to tell electron-builder to only attempt to publish to GitHub.

**Comment by 2xAA** [comment]
One thing to look out for is electron-builder's method of publishing seems to timeout on artefact publishing a lot, so platform builds may have to be restarted on Travis
