### ISSUE TITLE
Event Emitters for modV Plugins

### ISSUE THREAD

**Issue by 2xAA** [vcync/modV#39]
I've decided for the 1.6 Plugin system Event Emitters are a fairly good idea.  
It will keep modV Plugins abstract which will hopefully allow the creation of very complex or very minimal plugins.

Events are going to be added into 1.5, but the Plugin loader (Issue #38) will not be added until 1.6.

The reasoning behind this is that I can work on getting modV's API tidied up in 1.5 which will introduce a lot of breaking changes in one go (though none of these changes will break users' experience unless they've modified the code somehow).  
I can add the Emitters into the rebuilt internal API at the same time and all the code will be updated to ES6 also.

Let the madness ensue!

**Comment by TimPietrusky** [comment]
Sounds like a super good idea!

**Comment by 2xAA** [comment]
The current Event lists for the modV instance and each Layer instance, effective from commit 2cff0cb124be469d209cdc324b4b8a2349e46b83 on 1.5.
See the [EventEmitter2](https://github.com/asyncly/EventEmitter2) docs for implementation.

modV.on('eventID', value1, value2...)

| Event ID         | Values                                   |
| ---------------- | ---------------------------------------- |
| moduleRegister | Module[Module2D, Module3D, ModuleShader] |
| controlUpdate    | Control[Control, \*Control, CustomControl]        |
| layerAdd         | Layer[Layer], index[Integer]             |
| layerRemove      | Layer[Layer], index[Integer]             |
| layerReorder     | Layer[Layer], oldIndex[Integer], newIndex[Integer] |
| midiInput        | ??? (currently set to scope of modV.MIDIInstance - will most likely deprecate in favour of MIDI events being handled solely by a plugin) |



Layer.on('eventID', value1, value2...)

| Event ID        | Values                                   |
| --------------- | ---------------------------------------- |
| moduleAdd       | Module[Module2D, Module3D, ModuleShader], index[Integer] |
| moduleRemove    | Module[Module2D, Module3D, ModuleShader], index[Integer] |
| moduleReorder   | Module[Module2D, Module3D, ModuleShader], index[Integer] |
| enabledSet         | enabled[Boolean]                         |
| nameChange      | name[String]                             |
| clearingSet     | value[Boolean]                           |
| alphaSet        | value[Float]                             |
| enabledSet      | value[Boolean]                           |
| inheritSet      | value[Boolean]                           |
| inheritFromSet  | layerIndex[Integer]                      |
| pipelineSet     | value[Boolean]                           |
| drawToOutputSet | value[Boolean]                           |
| lockedSet          | value[Boolean]                           |
| blendingSet        | value[String]                            |

**Comment by 2xAA** [comment]
Other plugin APIs to add:

* ContextMenu hooks (rewrite current ContextMenu for NWJS feature parity)
* Interface panel hooks (by 2.0)
