### ISSUE TITLE
Input Breakpoints to change a property value for different thresholds

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#415]
**Is your feature request related to a problem? Please describe.**
When using an audio feature for a property, I want to change the value when it reaches a certain threshold, so that only then the audio feature kicks in, not all the time. 

**Describe the solution you'd like**
Configure a list of breakpoints that can force an update to the value, they could also overlap and then the order of the breakpoints (top to bottom or left to right) tells which one is "the main" one. In here I would also love to write down an expression to boost the value above the certain threshold, like then it reaches `value + 20%` it should be `value * 5.0` or `value / 1.2`.

**Comment by 2xAA** [comment]
Do you think this could be achieved with expressions, in #453?

**Comment by TimPietrusky** [comment]
@2xAA the purpose of this feature would be to have a UI component that somehow generates an expression, so yes, this could be achieved with expressions "low level", but I would still love to have a high level UI component at some point.
