### ISSUE TITLE
fails at npm start

### ISSUE THREAD

**Issue by venkat-oss** [vcync/modV#45]
Hi,

after cloning the repo and running npm install, I Ran the npm start command. it gave me the following error(attached txt file)

my node version is 6.9.0 as suggested.

[log.txt](https://github.com/2xAA/modV/files/908223/log.txt)

**Comment by 2xAA** [comment]
This is caused by issue #30. I have created issues on meyda's repo and a branch which will fix this issue. Please bear with this until the issue can be resolved.
