### ISSUE TITLE
[Color Picker] No UI to close pop-up

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#461]
**Operating system and application version**
 - OS: macOS
 - Version 3.3.8

**Describe the bug**
When you select a color, the color picker will stay open. It will also stay open if you close modV. 

**To Reproduce**
1. Add "bar"
2. Click on one of it's two colors
3. See that the color picker is open
4. Try to close it and see that this is not working

**Expected behavior**
I can select a color and hit enter or press a button and then the color picker is closing again.

**Comment by 2xAA** [comment]
This will be fixed, however it's closable using Chromium key combinations.

macOS: cmd+w
Windows/Linux: ctrl+w
