### ISSUE TITLE
[preset] Save / Load audio / video input config

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#470]
**Is your feature request related to a problem? Please describe.**
After configuring the audio / video input, it would be nice to save that into a preset and to be able to load it when the preset is loaded. 

**Describe the solution you'd like**
I save the preset, I load the preset and my audio / video config is restored. 

**Describe alternatives you've considered**
Set the audio / video config every time I start modV.

**Comment by 2xAA** [comment]
This can be added with `createPresetData` and `loadPresetData` actions in the relevant store module.
See `src\application\worker\store\modules\expressions.js` as an example.

**Comment by 2xAA** [comment]
@TimPietrusky Would it be preferable to save the audio and video inputs in modV's localStorage instead?
It would keep presets portable and most likely your audio and video setup won't need to change between presets on the same machine.

I'm also drawing inspiration from DAWs such as Ableton or Logic Pro X and A/V software like Resolume. Audio device in/out is stored as a user setting, not in the project file.

**Comment by TimPietrusky** [comment]
@2xAA yes that would be perfect!
