### ISSUE TITLE
Use jsdoc

### ISSUE THREAD

**Issue by 2xAA** [vcync/modV#48]
As suggested by pashutk, modV should use jsdoc for documentation.

This is an excellent idea. This issue will be kept open until the whole codebase has been documented.

**Comment by TimPietrusky** [comment]
👍

**Comment by 2xAA** [comment]
Is JSDoc flexible enough for this project?

I can't even seem to write a good `@typedef` documentation for an Object containing Functions.

See the **"Source Code"** tab [here](https://try.esdoc.org/#indexCode=%23%20Welcome%20to%20ESDoc%0A%0AThis%20is%20the%20place%20to%20try%20ESDoc.%20Please%20write%20a%20code%20and%20click%20%60Try%20it%20out%60!%0A%0A-%20%60Index%60%20(this)%20is%20used%20as%20a%20index%20page(Markdown).%0A-%20%60Source%20Code%60%20is%20used%20as%20a%20source%20code(JavaScript)%0A-%20%60Test%20Code%60%20is%20used%20as%20a%20test%20code(JavaScript).%0A-%20%60Manual(Usage)%60%20is%20used%20as%20a%20manual%20of%20usage(Markdown).%0A-%20%60Config%60%20is%20used%20as%20a%20configuration(JSON).%0A&sourceCode=%2F**%0A%20*%20modV%20Plugin%0A%20*%20%40typedef%20%7BObject%7D%20modvPlugin%0A%20*%0A%20*%20%40property%20%7Bfunction(Vue%3A%20Vue%2C%20%3F%3A%20Object)%7D%20install%20-%20Only%20called%20when%20added%20as%20a%20Vue%20plugin%2C%0A%20*%20this%20must%20be%20registered%20with%20vue%20before%20modV%20to%20use%20vuex%20or%20vue.%0A%20*%0A%20*%20%40property%20%7BFunction%7D%20modvInstall%20-%20Only%20called%20when%20added%20to%20modV.%0A%20*%0A%20*%20%40property%20%7Bfunction(arguments%3A%20Object)%7D%20process%20-%20Called%20once%20every%20frame.%20Useful%20for%20plugins%0A%20*%20which%20need%20to%20process%20data%20away%20from%20modV%0A%20*%20%60%60%60%0A%20*%20arguments.delta%20-%20The%20delta%20time%20of%20the%20frame%2C%20returned%20from%20the%20requestAnimationFrame%20loop%0A%20*%20%60%60%60%0A%20*%0A%20*%20%40property%20%7Bfunction(arguments%3A%20Object)%7D%20processValue%20-%20Called%20once%20every%20frame.%20Allows%20access%0A%20*%20of%20each%20value%20of%20every%20active%20Module.%20(see%20expression%20plugin%20for%20an%20example)%0A%20*%20%60%60%60%0A%20*%20arguments.currentValue%20-%20Current%20Value%20of%20Module%20Control%0A%20*%20arguments.moduleName%20-%20Name%20of%20Module%0A%20*%20arguments.controlVariable%20-%20Name%20of%20the%20Module%20Control%0A%20*%20%60%60%60%0A%20*%0A%20*%20%40property%20%7Bfunction(arguments%3A%20Object)%7D%20processFrame%20-%20Called%20once%20every%20frame.%20Allows%20access%0A%20*%20of%20each%20frame%20drawn%20to%20the%20screen.%0A%20*%20%60%60%60%0A%20*%20arguments.canvas%20-%20HTMLCanvasElement%20containing%20current%20modV%20output%20frame%0A%20*%20%60%60%60%0A%20*%2F&testCode=%2F**%0A%20*%20this%20is%20test%20for%20MyClass.%0A%20*%20%40test%20%7BMyClass%7D%0A%20*%2F%0Adescribe('test%20MyClass'%2C%20()%3D%3E%7B%0A%20%20%2F**%0A%20%20%20*%20this%20is%20test%20for%20MyClass%23method.%0A%20%20%20*%20%40test%20%7BMyClass%23method%7D%0A%20%20%20*%2F%0A%20%20it('has%20a%20method'%2C%20()%3D%3E%7B%0A%20%20%20%20assert(new%20MyClass(100).method)%3B%0A%20%20%7D)%3B%0A%7D)%3B%0A&manualCode=%23%20Usage%0A%0AThis%20is%20usage%20for%20MyModule%20that%20is%20written%20by%20GitHub%20Flavored%20Markdown.%0A%0A-%20this%20is%20list%20item1%0A-%20this%20is%20list%20item2%0A-%20this%20is%20list%20item3%0A%0A%60%60%60js%0Aconst%20myClass%20%3D%20new%20MyClass(100)%3B%0Aconst%20hello%20%3D%20myClass.method(1%2C%202)%3B%0Aconsole.log(hello)%3B%0A%60%60%60%0A&configCode=%7B%0A%20%20%22source%22%3A%20%22__SOURCE__%22%2C%0A%20%20%22destination%22%3A%20%22__DESTINATION__%22%2C%0A%20%20%22index%22%3A%20%22__INDEX__%22%2C%0A%20%20%22plugins%22%3A%20%5B%7B%0A%20%20%20%20%22name%22%3A%20%22esdoc-standard-plugin%22%2C%0A%20%20%20%20%22option%22%3A%20%7B%0A%20%20%20%20%20%20%22test%22%3A%20%7B%22source%22%3A%20%22__TEST__%22%7D%2C%0A%20%20%20%20%20%20%22manual%22%3A%20%7B%22files%22%3A%20%5B%22__MANUAL__%22%5D%7D%0A%20%20%20%20%7D%0A%20%20%7D%5D%0A%7D%0A)... 😕 

Maybe using something like [`vuepress`](https://vuepress.vuejs.org/) would be a better idea? Not sure yet.

Seems like for a lot of modV JSDoc (or ESDoc) would work out, but some bits are going to be tricky.

**Comment by TimPietrusky** [comment]
What is the problem in your example?

**Comment by 2xAA** [comment]
Sorry, with code maybe you can see the problem.

Functions as parameters of Objects seem to be impossible to document using ES/JSDoc:

This is a very basic modV Plugin, but I can't document the arguments of processFrame.

```JavaScript
export default {
  name: 'GrabCanvas',
  processFrame({ canvas }) {
    
  },
};
```

As in the example, I can write the arguments as Function types in ESDoc, then add some Markdown comments to explain those arguments, e.g.

```
 * @property {function(arguments: Object)} processFrame - Called once every frame. Allows access
 * of each frame drawn to the screen.
 * ```
 * arguments.canvas - HTMLCanvasElement containing current modV output frame
 * ```
```

But for me it breaks the ESDoc "@-rule" paradigm.

Ideally I can just use:

```
@function processFrame - Called once every frame. Allows access
@param arguments Object - Argument Object
@param arguments.canvas HTMLCanvasElement - Canvas containing current modV output frame
```

But this seems impossible in an Object `@typedef`.
