### ISSUE TITLE
Adding a module to a group via double-click is not working anymore

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#486]
**Operating system and application version**
 - OS: macOS & Ubuntu 16.04
 - Version: 3.7.0

**Describe the bug**
When I want to add a module to a group using a double click nothing happens. 

**To Reproduce**
1. Double click on any module
2. See that nothing happens
3. Click on any group to focus it
4. Do 1. again
5. See 2. again

**Expected behavior**
The module is added to the active group.

**Comment by 2xAA** [comment]
My changes in #480 broke this 😒
