### ISSUE TITLE
Resetting the layout shows a useless warning many times

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#497]
**Operating system and application version**
 - OS: macOS
 - Version: next

**Describe the bug**
When I reset the layout and have the dev tools open, I see a warning around 600 times. 

**To Reproduce**
1. Open the dev tools
2. View > Reset Layout
3. See the warning `inputs.js?0aca:77 Did not remove inputLink. Could not find input with id undefined` many times

**Expected behavior**
No warning is visible. 

**Additional context**
See #493

**Comment by 2xAA** [comment]
Fixed in #879!
