### ISSUE TITLE
Migrate from Travis to GitHub Actions

### ISSUE THREAD

**Issue by 2xAA** [vcync/modV#518]
Travis is creating difficulty with OSS and [have stopped their free credit program](https://travis-ci.community/t/oss-only-credits-request-processing-time-estimate/10446/6).

We should move to GitHub Actions, which gives 3000 GitHub Action minutes / month.
Assuming a complete build for mac / windows / linux takes 30 minutes (just super worst case), we have around 100 releases per month.

https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

**Comment by TimPietrusky** [comment]
This was already done.
