### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#521]
**Is your feature request related to a problem? Please describe.**
People are using videos when they compose their visual sets and want to use them in modV. 
People have a music video ready and want to apply some awesome effects in modV to use that for a live gig. 

**Describe the solution you'd like**
Use a component to add a video (e.g. `Texture 2D`) that provides playback methods for the video:
* Play / Pause video
* Change the playback speed
* Start time / end time of the snippet of the video
* Restart video automatically vs play only once
* Loop video

**Describe alternatives you've considered**
See https://github.com/vcync/modV/discussions/501#discussioncomment-197293

**Comment by 2xAA** [comment]
We may be able to support video without moving outside of the worker, but we may need extra node.js conversion steps.
For example, .basis Universal Texture Video can be used without `<video>` or DOM APIs: http://binomial.biz/TextureVideoTest/

**Comment by TimPietrusky** [comment]
We are working on getting support for this via https://github.com/vcync/modV/issues/569

**Comment by 2xAA** [comment]
Realistically, #569 is a long way off and should probably be part of "modV 4", whenever that happens.

But, as all things Chromium transpire, you wait long enough and there's a new API to use.
This explains how to decode an MP4 in a Worker and extract frames:

https://w3c.github.io/webcodecs/samples/mp4-decode/

Other resources:
https://gpac.github.io/mp4box.js/#seektime-userap
https://web.dev/webcodecs/
https://developer.mozilla.org/en-US/docs/Web/API/WebCodecs_API

---

Could be viable. Slow down only really occurs on multiple 1080 videos.
Stress test here: https://cn363.csb.app/

**Comment by 2xAA** [comment]
#695 is related as it will essentially use the same interface.

This is an updated stress test using the preferred method of sending the whole video stream to the worker, rather than frames. https://r3w32.csb.app/
