### ISSUE TITLE
Add all ISF modules from Vidvox into modV

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#541]
All the modules from https://github.com/Vidvox/ISF-Files/tree/master/ISF are under MIT and we could add them into modV.

**Comment by TimPietrusky** [comment]
@2xAA What do you think? Should we give this a try?

**Comment by 2xAA** [comment]
Let's try it!

I know for sure the JavaScript ISF renderer is broken for some operations for some ISF modules in modV already, but we can see what works.

**Comment by TimPietrusky** [comment]
I'm on it!

**Comment by TimPietrusky** [comment]
These can't be added as audioFFT is not supported by isf-js:

* FFT Color Lines.fs
* FFT Filled Waveform.fs
* FFT Spectrogram.fs
* Radial Spectrogram
* Waveform Displace

These modules are not added as they use "non-constant expression" (usually in a loop) or "Index expression must be constant", which is annoying to convert:

* Chroma Mask
* Chroma Desaturation Mask
* Color Bars
* Color Organ Polyphonic
* Color Replacement
* Dilate-Fast
* Dilate
* Duotone From Histogram
* Erode-Fast
* Erode
* God Rays
* Motion Heat Map
* Motion Mask
* Poly Glitch
* Thermal Camera
