### ISSUE TITLE
Golden Layout is causing a performance drop when switching between modules

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#545]
**Operating system and application version**
 - OS: MacOS / Windows 10
 - Version: 3.11.0

**Describe the bug**
When clicking on a module and then on another module to open the module inspector, there is a lag until the inspector is updated. This has an influence on  the whole main thread. 

**To Reproduce**
1. Add two modules
2. Click on one module to open the module inspector
3. Start the Chrome profiler
4. Click on another module
5. Stop the Chrom profiler
6. See that there is a lag of about 500 ms when Golden Layout is opening the module inspector

**Expected behavior**
There is not lag.

**Comment by 2xAA** [comment]
Golden Layout 2 seems like a solution to this problem.
It removes jQuery which is where we've seen the lag occur.

In the Golden Layout 2 README, there's an example of natively using GL2 with Vue 3, so we'll need to upgrade to Vue 3 before upgrading to GL2.

https://github.com/golden-layout/golden-layout#vue
