### ISSUE TITLE
Move away from OffscreenCanvas

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#569]
* This will allow images (SVG) and videos to be used much easier
* Grandiose will "just" work

## Concerns
* Some stuff will break
* Gallery Preview could be limited to improve performance

## Ideas
* Put Audio into render-thread
* `Output Preview` video.requestPictureInPicture 
  * Or https://stackoverflow.com/questions/42218566/copy-canvas-image-from-a-browserwindow-to-another-at-60fps-in-atom-electron
  * https://codesandbox.io/s/canvas-pip-qrqdx?file=/src/index.js:392-405
  * https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/stop

**Comment by 2xAA** [comment]
Closing this as I don't really think it's needed anymore, especially with the addition of the MediaCodec API (#696, #695).
SVG can be handled easily enough by rendering to a Canvas in the DOM and transferring to the worker.
