### ISSUE TITLE
Missing font

### ISSUE THREAD

**Issue by pashutk** [vcync/modV#57]
<img width="422" alt="screen shot 2017-04-16 at 02 24 46" src="https://cloud.githubusercontent.com/assets/4306737/25067427/fe1beb80-224b-11e7-974f-c1d978e9862c.png">

Error in console: missing Arimo-regular font. It's used in nwjs styles.
Needs to be restored or removed.

**Comment by 2xAA** [comment]
This is for [nwjs-browser-menu](https://github.com/2xAA/nwjs-menu-browser). I'll create an npm package for this as soon as I can and import it that way, then the font issue will be fixed.

**Comment by pashutk** [comment]
Resolved in #59
