### ISSUE TITLE
Expressions are not working anymore

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#594]
**Operating system and application version**
 - OS: Ubuntu 20.04
 - Version: 3.17.1

**Describe the bug**
When you enter something into an `expression`, and error is shown in the console.

**To Reproduce**
1. Add a module to a group
2. Click on a property of the module
3. Expand "expression" in the `Input Config`
4. Do any change in the textarea and click outside of it
5. See that there is an error in the console

```js
Worker caught an error: TypeError: Cannot read property 'parse' of undefined
    at compileExpression (expressions.js?8a2f:24)
```

**Expected behavior**
We can change the expression.

**Additional context**
When starting modV in dev-mode, I see this message:

```js
warning  in ./src/application/worker/store/modules/expressions.js
"export 'default' (imported as 'math') was not found in 'mathjs'
```

**Comment by 2xAA** [comment]
[mathjs.patch.txt](https://github.com/vcync/modV/files/6715145/mathjs.patch.txt)

This will fix things, but I'd like to investigate _why_ this happened. Packages shouldn't just suddenly break like that.

**Comment by 2xAA** [comment]
https://github.com/vcync/modV/pull/582

It was _PAST ME_ 😧 

Not sure why dependabot is suggesting we jump major versions, but I should've reviewed more carefully.
