### ISSUE TITLE
A module with the same name can't exist more than once

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#600]
**Operating system and application version**
 - OS: Any
 - Version: 3.17.1

**Describe the bug**
When adding the same module twice (e.g. as one as shader, the other as ISF), then we see a bunch of errors in the console. 

**To Reproduce**
* Create a module called `Lines` in the in `modV/media/default/module` of type `shader`
* Load the branch `feat/541/vidvoxIsfModules` which contains an ISF module called `Lines`
* See these errors:

```
modules.js#removeActiveModule: Cannot destructure property 'meta' of 'module' as it is undefined.

loop.js: Cannot read property 'meta' of undefined

loop.js: Cannot destructure property 'meta' of 'module' as it is undefined.

modules.js#init: Cannot read property '$moduleName' of undefined
```

Not all of them are shown all the time, but if the module-name-conflict is resolved, none of them are shown. 

What I also see is this warning a couple of times:

```
Did not remove inputLink. Could not find input with id
```

**Expected behavior**
We can use modules, even when they have the same name.

**Comment by 2xAA** [comment]
### 🎉 Issue 600 🥳
Just to clarify on the "Expected behaviour" - we shouldn't need a message about a naming conflict, it should just work.

Names really only should be a visual label.

I can't think of anything that would be using the module name as a key in the code anymore.

**Comment by TimPietrusky** [comment]
@2xAA I updated the "expected behaviour" as you are super right. Doesn't make sense that the name is producing a problem. I even saw a warning like `Module registered with name "${name}" already exists.`, see https://github.com/vcync/modV/blob/next/src/application/worker/store/modules/modules.js#L95, which sometimes was shown after all the other errors, but only sometimes. Not sure how to reproduce it.

**Comment by 2xAA** [comment]
@TimPietrusky This must be left-over functionality from modV 2. No idea why I left that there.

**Comment by 2xAA** [comment]
> @TimPietrusky This must be left-over functionality from modV 2. No idea why I left that there.

@TimPietrusky excellent foreshadowing

**Comment by TimPietrusky** [comment]
We worked on this, but then realized that this change will break presets, as those only can rely on the name of a module right now. We have to think of something else.

**Comment by TimPietrusky** [comment]
# Workaround

Rename the module.
