### ISSUE TITLE
[Linux] Snap package has no access to . (dot) folders

### ISSUE THREAD

**Issue by 2xAA** [vcync/modV#615]
**Operating system and application version**
 - OS: Linux
 - Version *

**Describe the bug**
Snap packages don't have access to dot folders which is a problem for modV as the media folder is created in `~/.config/modV/`. No custom media can be loaded into modV.

**To Reproduce**
1. Install the Snap package
2. Try to load any custom modules or media

**Expected behavior**
We'd be able to access the filesystem normally.

**Screenshots**
n/a

**Additional context**
Snap packages aren't auto-updatable outside of the Snap store and we can't currently build the package non-classically, so we can't use the Snap store - maybe we should stop supporting Snap?

@TimPietrusky also reported slowdown in using the Snap package, so could be another case to remove the snap build entirely.

**Comment by TimPietrusky** [comment]
We should stop supporting Snap, as the AppImage is totally enough to get everything working.

**Comment by 2xAA** [comment]
I think it would be nice to figure out some way to have modV actually installed to the system, not through Snap. I don't think you can install AppImages like you can snap packages.

**Comment by TimPietrusky** [comment]
@2xAA yeah I mean that would be fine, but as there is no demand yet to have this AND we have a way to actually use it on Linux, we should not invest more time into this. But if you disagree, let's open a new ticket for this.

But for now, I think we should remove the snap-package entirely: #637
