### ISSUE TITLE
ModuleScript is broken in GrabCanvas

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#63]
It doesn't work! 

I think you should remove it and "GrabCanvas" should be a plugin. 

Is that a good idea?

**Comment by 2xAA** [comment]
Yes, my thoughts exactly

**Comment by TimPietrusky** [comment]
Awesome!

**Comment by 2xAA** [comment]
8fe5506 re-writes GrabCanvas to a modV 2.0 Plugin. I think this fixes the issue - can you confirm?

**Comment by TimPietrusky** [comment]
It does, thank you!
