### ISSUE TITLE
Loading "bool" from preset is not working (WIP)

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#644]
**Operating system and application version**
 - OS: macOS
 - next

**Describe the bug**
When changing the value of a bool attribute in ISF and save it into a preset, it doesn't get loaded as it was saved. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by 2xAA** [comment]
This issue is not just with ISF, it's across all modules.
Properties aren't handled differently per renderer.
