### ISSUE TITLE
Why do we need "aws-sdk"?

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#705]
When doing https://github.com/vcync/modV/pull/657 I was trying to find out why we use `aws-sdk`  as it is added as a `dependency` in `package.json`, but couldn't find a reason. It was added here: https://github.com/vcync/modV/commit/57da5d46cd34e374aa96371d1266498243e6ab1e#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R19

@2xAA do you have an idea?

**Comment by 2xAA** [comment]
Yeah not quite sure.
I remember it was a missing dependant of a library, but we may have removed
this?

Let's do some discovery.

**Comment by 2xAA** [comment]
@TimPietrusky Just tried removing the package and everything seems okay.
