### ISSUE TITLE
Texture 2D is not showing an "image" anymore

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#706]
**Operating system and application version**
 - OS: macOS
 - Version: next

**Describe the bug**
When using `Texture 2D` > `image`, the image is not shown anymore. 

**To Reproduce**
1. Add `Texture 2D`
2. Select `image`
3. Select any image
4. See that the image is not shown

**Expected behavior**
The image is shown. 

**Additional context**
When testing https://github.com/vcync/modV/pull/655 it was still working, but then I was checking another PR and saw that the same bug occurred. My first intention was that this was related to the PR https://github.com/vcync/modV/pull/657, but then I also saw this error in another PR and tested it in `next`. And there was the same problem.

**Comment by TimPietrusky** [comment]
It is also not working for me in `main`, maybe something on my mac is the problem. Need some second pair of eyes 🙈

**Comment by TimPietrusky** [comment]
It is also not working for me when using the latest release https://github.com/vcync/modV/releases/tag/3.20.2

**Comment by 2xAA** [comment]
I guess it got broken with #661?
