### ISSUE TITLE
[ThreeJS] Preset contains camera + scene

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#711]
**Operating system and application version**
 - OS: macOS
 - Version: 3.21.0

**Describe the bug**
When using a ThreeJS-Module and saving a preset, everything in `data` gets saved into the preset, making the preset super big. 

**To Reproduce**
1. Add a ThreeJS-Module into a group
2. Save the preset
3. See that under `models > data` we can find `camera` and `scene`

**Expected behavior**
This is not saved into the preset as that information is totally useless and blows up the preset. I have a scene with an glTF model loaded and the preset has 2.8 MB.

**Comment by 2xAA** [comment]
@TimPietrusky True.

Camera shouldn't be saved, but what about the scene data?

Unless a strict requirement is that all the scene object's state can be derived from the module's props or data, i.e. how many children, their scale, rotation, etc.

It's possible to serialize the scene data and load it back again:
https://discourse.threejs.org/t/the-best-way-to-save-and-open-three-js-scene/16158

Saving the scene data could be a module option in the module meta.
