### ISSUE TITLE
Increase audio input gain directly in meyda

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#727]
**Is your feature request related to a problem? Please describe.**
Increase the gain in meyda, so that the input audio can be controlled.

**Describe the solution you'd like**
Audio Gain component in the bottom bar next to fps. 

**Describe alternatives you've considered**
Increase the volume in the application that is playing back the audio. Having an external audio interface that can increase the gain, but for the price of having distorted audio. I want to keep the original audio input untouched, so that I can still record it.

**Comment by 2xAA** [comment]
Why would increasing the audio gain before modV result in unusable clipped audio?
If you're clipping it's definitely too loud at that point and it's unusable for clean visuals.

If more gain is required, use expressions and multiplication or fix your audio setup.

**Comment by TimPietrusky** [comment]
I want to boost the whole value, so that all my expressions are boosted at once.
