### ISSUE TITLE
open preset can't access all preset files

### ISSUE THREAD

**Issue by tabroughton** [vcync/modV#772]
**Operating system and application version**
 - linux, kernel 5.19, Manjaro (Arch based), kde desktop

**Describe the bug**

I thought this was a bug that the files weren't being created when saving presets but I was wrong.
What actually is happening is that the open preset is only looking for `.json` files but the save preset allows you to save any files, in fact you have to type `.json` as the file extension for it to work.

How I was using it was saving a preset and calling it anything like `modVpreset` but then when opening it using `open preset` the dialog doesn't show the files that were saved.  (I thought this was a bug that the files weren't being created).

But then I found the files on the system.   I believe `open preset` will only show files that have `.json` extension, when I used the `save preset` and then saved the file as `modVpreset.json` I could then open them.  

I think this is a bug because there is no suggestions you need to save a file with this extension so either the save operation should append a `.json` to the name you enter or the open operation should allow you to browse any file type in the file browser dialogue.  

**To Reproduce**
1. Add some modules to a group
2. Click on `file->save preset`
3. select a location and add a file name in the file browser without a `.json` extension
4. Click save
5. Close modv and open again or click `view`->`reload`
6. click `open preset`
7. Browse to where you think you saved your preset
8. It can't be seen or loaded in the file browser dialogue

**Expected behavior**
I am able to see the preset file so I can select it to load the preset

**Screenshots**
n/a

**Additional context**
n/a

**Comment by 2xAA** [comment]
Thanks for the bug report, @tabroughton!

According to one of Electron's maintainers this is apparently this is intended behaviour for Electron on Linux?!
https://github.com/electron/electron/issues/21935#issuecomment-580064114

But, there seems to be a workaround, will try this tonight.
https://github.com/jamovi/jamovi/commit/38a0cfc9fca392a03eb074611b67deda6cb66b1c
