### ISSUE TITLE
Active Module and Group titles should show a `grab` cursor

### ISSUE THREAD

**Issue by 2xAA** [vcync/modV#822]
When hovering an Active Module or Group title the cursor should be set to `grab`.
Additionally when the item is being grabbed the cursor should be set to `grabbing`.

re #821

**Comment by Yasir761** [comment]
Can you provide more information on this

**Comment by 2xAA** [comment]
Hey @Yasir761 - what do you need context on here?

**Comment by Yasir761** [comment]
I was going through repo but I'm not able to find Group title

**Comment by 2xAA** [comment]
Hi @Yasir761 - the Group title is here:
https://github.com/vcync/modV/blob/next/src/components/Group.vue#L182

The active module title is here:
https://github.com/vcync/modV/blob/next/src/components/ActiveModule.vue#L10
