### ISSUE TITLE
Module properties not updated correctly when selection changes

### ISSUE THREAD

**Issue by HorstBaerbel** [vcync/modV#892]
**Operating system and application version**
 - OS: Fedora
 - Version 3.29.1

**Describe the bug**
With module of the same type the properties of the first selected module are shown, not the actual selected node. Switching between nodes of the same type does not fix that behaviour. Selecting a **different** module type, then again the second module, fixes it.

**To Reproduce**
1. Add module type and change some settings
2. Add second module of same type -> settings of first node are shown

**Expected behavior**
Correct properties are shown

**Comment by 2xAA** [comment]
I can't reproduce this. Is it just two of the same module in the same group that causes this behaviour?

**Comment by HorstBaerbel** [comment]
Can't reproduce this either. Not sure how I did this, it's been a long time...
