### ISSUE TITLE
Unable to build on Fedora 40

### ISSUE THREAD

**Issue by HorstBaerbel** [vcync/modV#914]
**Operating system and application version**
 - OS: Fedora 40
 - Version: next/latest

**Describe the bug**

> yarn install v1.22.22
> [1/4] Resolving packages...
> warning Resolution field "electron-builder@23.0.2" is incompatible with requested version "electron-builder@^22.2.0"
> [2/4] Fetching packages...
> error @achrinza/node-ipc@9.2.6: The engine "node" is incompatible with this module. Expected version "8 || 9 || 10 || 11 || 12 || 13 || 14 || 15 || 16 || 17 || 18 || 19". Got "20.12.2"
> error Found incompatible module.

**To Reproduce**
1. Clone repo and go to modV directory
2. Install yarn (yarnpkg-1.22.22-2.fc40.x86_64)
3. Run yarn

**Expected behavior**
Build succeeds

**Additional context**
Total JS noob here. I just wanted a new build and tried the obvious from the Repo README. I'd shut up if there was a recent release.

**Comment by 2xAA** [comment]
I need to update the project to use Node 20.

As Node 18 is still in LTS, you can switch your Node version to 18 using nvm:
https://nodejs.org/en/download/package-manager

```bash
# installs nvm (Node Version Manager)
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

# download and install Node.js (you may need to restart the terminal)
nvm install 18

# verifies the right Node.js version is in the environment
node -v # should print `v18.20.4`

# verifies the right npm version is in the environment
npm -v # should print `10.7.0`
```

**Comment by 2xAA** [comment]
Found a bit of time to update this. There's a new Linux build in the releases.
